### ISSUE TITLE
New England states are insane

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#103]
Requires `level=fipscode` or else results are returned at the township level, as I remember from the time @harrisj lost his mind. Might need to exclude New England states from the standard call and make a second just for their results.

Sigh.

**Comment by eads** [comment]
fantastic! :/ :/ :/

On Thu, Nov 19, 2015 at 4:09 PM, Jeremy Bowers <notifications@github.com>
wrote:

> Requires level=fipscode or else results are returned at the township
> level, as I remember from the time @harrisj <https://github.com/harrisj>
> lost his mind. Might need to exclude New England states from the standard
> call and make a second just for their results.
>
> Sigh.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/103>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
Yeah, this is either going to require:
* A second API call to get the same results as all the other states.
* A tedious effort of following a map of FIPS-to-city-names to knit them together.

I vote for a second API call so we don't have to do math.

**Comment by jeremyjbowers** [comment]
I guess we could request ALL things as `level=fipscode` and then we'll just have to do a quick lookup to determine the county's name. http://www2.census.gov/geo/docs/reference/codes/files/national_county.txt

This might be best, actually.

**Comment by eads** [comment]
I like that idea, given what a premium API calls are at.

On Thu, Nov 19, 2015 at 4:19 PM, Jeremy Bowers <notifications@github.com>
wrote:

> I guess we could request ALL things as level=fipscode and then we'll just
> have to do a quick lookup to determine the county's name.
> http://www2.census.gov/geo/docs/reference/codes/files/national_county.txt
>
> This might be best, actually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/103#issuecomment-158201210>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by harrisj** [comment]
API calls are at a premium, but if you can request AP results at the town level, it does let you do cool granular maps like this http://elections.nytimes.com/2012/primaries/states/new-hampshire

**Comment by mericson** [comment]
we'll want both county and township level maps, so should pull and store
both,

**Comment by eads** [comment]
@jeremyjbowers I had been wondering about this... we probably need a mechanism for specifying the result level both in the Python API and via the CLI.

**Comment by jeremyjbowers** [comment]
Should talk this out f2f on Tuesday.

**Comment by jeremyjbowers** [comment]
Will just do rollup with FIPS codes. One API call!

**Comment by jeremyjbowers** [comment]
Making a new ticket to represent the actual work; this ticket will represent the decision we made.
