### ISSUE TITLE
BallotPositions don't have unique ids, somehow?

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#106]
Good catch, @wmandrews. 
![screen shot 2015-11-20 at 5 08 43 pm](https://cloud.githubusercontent.com/assets/109988/11313240/6fd15d0a-8fa9-11e5-8763-f3f1ade3659d.png)

**Comment by harrisj** [comment]
This reminds me. The AP will assign arbitrary race numbers to Ballot Measures that don't reflect their real number (indeed in some states, it will appear on the ballot as something like Amendment B or Proposition 1101-3). You'll need to have some other mechanism for ordering ballot measures on your page and be able to handle different names (I've seen one state have both Amendment 1 and Question 1 on a ballot)

**Comment by eads** [comment]
We've been thinking a lot about how to handle manual ordering, name
overrides, etc. In the demo implementation, once data is loaded a view is
created which joins a name override table to the results. Then you just
query the view. The same could be done here.

**Comment by harrisj** [comment]
Yep, that was one of the many uses of our `nyt_races` table which mapped our race information onto ballot initiatives.

**Comment by harrisj** [comment]
Oh! One last thing about them, the AP will prefix "special" choices like Yes or No (for Ballot Initiatives) or None of the Above by prefacing their full value with a space like `" Yes"`. You're not hallucinating that.

**Comment by wmandrews** [comment]
Dear god

**Comment by harrisj** [comment]
They've always done that. It just hasn't made any problems when inside a
HTML page because it's just whitespace

**Comment by jeremyjbowers** [comment]
Got this in sha 6142211df801f997076ef04eeb5fe78b1a5056a6.
