### ISSUE TITLE
eliminate `set_fields`

### ISSUE THREAD

**Issue by eads** [newsdev/elex#117]
explicitly set properties in constructor, e.g.:

```python
def __init__(self, raceTypeID):
    self.racetypeid = raceTypeID
```

**Comment by jeremyjbowers** [comment]
On this. Slow going, but on it.

**Comment by jeremyjbowers** [comment]
Found some duplicated fields!

**Comment by eads** [comment]
Yeeeeah, there were some dupes in there, not that they do much harm. Good
to weed 'em out.

On Mon, Nov 30, 2015 at 10:09 AM, Jeremy Bowers <notifications@github.com>
wrote:

> Found some duplicated fields!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/117#issuecomment-160656052>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
