### ISSUE TITLE
Documentation: recipes

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#118]
- [x] CLI -> CSV -> Postgres
- [ ] CLI -> JSON -> s3cmd (or something) to S3
- [x] Python module -> Python objects
- [ ] Python module -> Django management command -> Django models

**Comment by eads** [comment]
Rando thoughts:

The recipes could always use your lovely candidate reporting units data for
each example since that's all you really need.

Json is written to stdout so you could literally pipe directly to S3(!!).

**Comment by jeremyjbowers** [comment]
The CLI -> CSV -> Postgres example is here: https://github.com/newsdev/ap-election-loader/blob/master/update.sh

**Comment by jeremyjbowers** [comment]
Python modules just harvested from `tests/__init__.py`.
```
from elex.parser import api

# Setup and call the AP API.
e = api.Election(electiondate='2015-11-03', datafile=self.data_url, testresults=False, liveresults=True, is_test=False)
raw_races = e.get_raw_races()
race_objs = e.get_race_objects(raw_races)

# Get lists of Python objects for each of the core models.
ballot_measures = e.ballot_measures
candidate_reporting_units = e.candidate_reporting_units
candidates = e.candidates
races = e.races
reporting_units = e.reporting_units
results = e.results
```

**Comment by jeremyjbowers** [comment]
Will save s3 and Django for future milestones.
