### ISSUE TITLE
State level vs national level results

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#120]

**Comment by eads** [comment]
proposal:

```bash
elex stateresults 2015-11-03 IL
```

Omit the state argument for all states.

**Comment by jeremyjbowers** [comment]
So, I think this needs to get implemented in the CLI? The correct call is with a `national=false` flag. I need to look up the state flag, but I think it's a comma-separated list.

**Comment by jeremyjbowers** [comment]
I'm pushing this back one release -- neither NH nor IA have any local results. They're just presidential primaries / caucuses. Super Tuesday DOES have some local races to be aware of.
