### ISSUE TITLE
Response caching

### ISSUE THREAD

**Issue by eads** [newsdev/elex#121]

**Comment by jeremyjbowers** [comment]
This is actually maybe better to handle in the loader implementation? See https://github.com/newsdev/elex-loader/issues/23. Elex has a really handy `-d` flag to point to a cached local data file.

**Comment by eads** [comment]
I think the way to do this would be to use http://cachecontrol.readthedocs.org/en/latest/

On some level, I like this better than https://github.com/newsdev/elex/pull/241 which does some slightly weirder and less generalized stuff to cache just one result. 

I'm not delighted by the indirection this would add to network calls, which would be a reason to stick with the above PR or add a `--reports-file` argument and you can cache the reports response yourself in your loader.

On the other hand, a correct/careful CacheControl implementation would work fine now and have the advantage of working correctly with any caching improvements the AP makes in the future. 

On the other other hand, as long as the API's caching responses don't work right, it might not actually help minimize the # of requests against the quota without additional work.

In all events, I'm gonna try it and tell you what I find out!
