### ISSUE TITLE
Tests rely on an API key

### ISSUE THREAD

**Issue by rshorey** [newsdev/elex#127]
not necessarily terrible, but it will prevent people with no API access from running tests, and should probably be excluded from CI.

**Comment by eads** [comment]
Yeah... and it's only one set of tests. I don't know enough about nose best practices for handling such a situation, though. Maybe skip the network tests if no key is configured? Or provide two test runner modes?

**Comment by rshorey** [comment]
I think specifying not to run it won't be a problem, my concerns are:

1) If we're counting on CI to do our test running and those tests aren't running, there's a much greater chance of screwing something up

2) If anyone is thinking of using the software and wants to test it, an important chunk will remain untested for them

@jeremyjbowers said there's some work afoot to request test API keys, so I'm going to hold off on this until we get an answer on that
