### ISSUE TITLE
tests should be split into one assertion per test

### ISSUE THREAD

**Issue by eads** [newsdev/elex#135]
I'm sorry @jeremyjbowers :/

**Comment by jeremyjbowers** [comment]
Is this convention valuable in all cases?

For example:
```
    def test_ballot_measure_attributes(self):
        c = self.ballot_measures[0]
        self.assertEqual(c.last, "Yes")
        self.assertFalse(hasattr(c, 'first'))
        self.assertEqual(c.unique_id, "12482")
```
This contains three assertions, all testing the same thing -- if a ballot measure has the attributes we expect.

Is the correct thing to make three tests that duplicate function? Or to remove two of the assertions and make the tests more brittle?

**Comment by jeremyjbowers** [comment]
I am not an idiomatic Python test-writer, so I expect to be totally wrong. But which direction should we go? Split each up and make more tests or remove assertions?

**Comment by jeremyjbowers** [comment]
Finally. Got this in sha 7d337997bb11afb0db2552a24fe7c1edb38495cd and 34d9cc059c202dca7e444c7dcec0320fe0ad9fe3
