### ISSUE TITLE
Add methods for delegate counts

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#138]
Get with the AP in order to figure this out.

**Comment by jeremyjbowers** [comment]
For example, Iowa has ~122 delegates. We'd want to figure out how those are distributed.

**Comment by wmandrews** [comment]
We also just need to know how many each state has to give out in total, if it can be parsed from their data. You can reference [this page](http://int-static-stg.s3-website-us-east-1.amazonaws.com/elections/elections/2016/primaries/iowa) and other states to see AP's estimates from earlier this year.

**Comment by eads** [comment]
I think we should try to get this in by next Weds, Jan 13, to catch the next big test. I don't think we'll get the one that's in 15 minutes (:

**Comment by jeremyjbowers** [comment]
But, I am capturing from the API right now every 90 seconds! So we'll have
test data.


contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])

**Comment by eads** [comment]
You are the best.

**Comment by jeremyjbowers** [comment]
Okay, got this in sha 573752d49a55380eab4189fa5fa80b6213ebc958.
