### ISSUE TITLE
from elex.api.api import Election etc is rather ugly

### ISSUE THREAD

**Issue by eads** [newsdev/elex#146]
I think:

```
from elex.api import Election
```

or maybe...

```
from elex.api.models import Election
```

or just...

```
from elex import Election
```

This applies to all model-type classes.

**Comment by eads** [comment]
@jeremyjbowers whaddya think?

**Comment by jeremyjbowers** [comment]
Sure, I can get behind this.

**Comment by jeremyjbowers** [comment]
Let's do from elex import Election and we'll just overload elex/__init__.py with all the stuff in api/*.py

**Comment by jeremyjbowers** [comment]
Got this in sha 750a7e9f874b971a4d6774aefccbd0e699d2b03d.
