### ISSUE TITLE
should unique IDs contain election date?

### ISSUE THREAD

**Issue by eads** [newsdev/elex#149]
This would be extremely useful for any kind of admin interface or situation where multiple elections might go in a single database. And why not?

**Comment by eads** [comment]
Might also make sense to make a field on every row.

**Comment by jeremyjbowers** [comment]
Sure.

**Comment by jeremyjbowers** [comment]
Yeah, `electiondate` is going to travel down from `Election` to `Race` to `ReportingUnit` to `CandidateReportingUnit.`

It will **not** be on the `Candidate` or `BallotMeasure` objects so that these can be re-used across elections.

**Comment by jeremyjbowers** [comment]
This cannot be true for candidate `unique_ids` or candidate reporting unit `unique_ids` if we want to have persistent candidate objects.

**Comment by jeremyjbowers** [comment]
Need to talk this out with @eads.

**Comment by eads** [comment]
Makes sense to me to omit from candidate. But shouldn't it be on candidate
reporting unit?

On Tue, Dec 22, 2015 at 7:50 PM, Jeremy Bowers <notifications@github.com>
wrote:

> Need to talk this out with @eads <https://github.com/eads>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/149#issuecomment-166770047>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
