### ISSUE TITLE
Add short requirements section to readme

### ISSUE THREAD

**Issue by eads** [newsdev/elex#150]

**Comment by eads** [comment]
@raydaly happy to kick this to you if interested, otherwise I'll take it since we're rolling a release weds

**Comment by raydaly** [comment]
Go ahead and take it.

**Comment by eads** [comment]
Thanks!

On Tue, Dec 22, 2015 at 4:54 AM, Ray Daly <notifications@github.com> wrote:

> Go ahead and take it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/150#issuecomment-166570092>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
