### ISSUE TITLE
Results have votecount but not votepct for Super Tuesday.

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#152]
![screen shot 2015-12-21 at 2 48 32 pm](https://cloud.githubusercontent.com/assets/109988/11939718/ef4fa98c-a7f1-11e5-83d8-f2c535d474fa.png)

**Comment by jeremyjbowers** [comment]
Maybe this is just bad test data?

**Comment by eads** [comment]
You know, I thought we had bad test data last time around, and it turned out to be a bug in mah code. Well, okay, it happened several times and every time but once it was bad data. But still!

**Comment by jeremyjbowers** [comment]
HAH

**Comment by jeremyjbowers** [comment]
It's definitely a bug. I now have a test for this (there wasn't a test before, BAD JEREMY BAD) and it's failing.
