### ISSUE TITLE
when specifying datafile and getting next election, date MUST be specified

### ISSUE THREAD

**Issue by eads** [newsdev/elex#161]
is this the desired behavior? if so, document. If not, change.

**Comment by jeremyjbowers** [comment]
I don't understand this issue. Is it a bug, @eads ?

**Comment by eads** [comment]
Well, kind of. It's just that you have to provide an election date even
when loading from files. But if you provide files, the election date could
be any parseable date -- it's just ignored. Does that make sense?

On Thu, Feb 25, 2016 at 1:41 PM, Jeremy Bowers <notifications@github.com>
wrote:

> I don't understand this issue. Is it a bug, @eads
> <https://github.com/eads> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/161#issuecomment-188923133>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
I'll look at this but might wind up pushing it. I fear there's some code cul-de-sacs I might wind up in.
