### ISSUE TITLE
should 'level' ever be null/None?

### ISSUE THREAD

**Issue by eads** [newsdev/elex#174]

**Comment by jeremyjbowers** [comment]
No; it should be one of 'state', 'township' or 'county.'

**Comment by eads** [comment]
Whee. In some cases it appears it is null.

On Thu, Jan 7, 2016 at 3:27 PM, Jeremy Bowers <notifications@github.com>
wrote:

> No; it should be one of 'state', 'township' or 'county.'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/174#issuecomment-169795827>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
What data set are you using to get these nulls? 2012 General?

**Comment by jeremyjbowers** [comment]
This is true for some old data in 2012 and apparently one of the 2015 elections. Cannot duplicate in 2016 primary data.
