### ISSUE TITLE
Should reporting units carry candidates?

### ISSUE THREAD

**Issue by TylerFisher** [newsdev/elex#177]

**Comment by jeremyjbowers** [comment]
Explain?

**Comment by eads** [comment]
@TylerFisher and I were looking at using reporting units in a relational model to capture results, which I recalled were per-candidate with results (just without race info), but that was just wrong. 

It's still a little confusing though to think about how to make a relational model out of all this stuff -- specifically to build one with results that *aren't* denormalized. 

Additionally, reporting units do come with a votecount field, which I assume is votes for all candidates. 

Something to talk about on the call today.

**Comment by jeremyjbowers** [comment]
Yes, I understand the problem and I think I have a rational answer.


contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])

**Comment by jeremyjbowers** [comment]
We talked about this. Closing now.
