### ISSUE TITLE
Explore using movie.py to create "news crawl" with results data for video

### ISSUE THREAD

**Issue by ryanpitts** [newsdev/elex#195]
Pietro spotted this possibility: http://zulko.github.io/moviepy/index.html

**Comment by eads** [comment]
YESSS. In general, export to video captioning / data feed formats would be fucking awesome. Let's get this thing feeding CNN.

**Comment by pietrop** [comment]
I am trying to round up some specs of input and output for these kind of things, but also been playing a round with BBC video compositor, which could lend itself nicely for something like this (with a web video output) as it supports making videos with multiple tracks..

https://github.com/bbc/html5-video-compositor 
 http://www.bbc.co.uk/rd/blog/2015-11-open-source-html5-video-compositor

**Comment by Laurian** [comment]
If you already have SRT, with movie.py is this simple: https://gist.github.com/Laurian/32c39ae896ee8b22fab7

**Comment by ryanpitts** [comment]
Linking up @pietrop's project here: https://github.com/OpenNewsLabs/elex-webVideoTextCrawler
