### ISSUE TITLE
votepct uses normal form (0.3 for 30%) but precinctsreportingpct multiples by 100 (30 for 30%)

### ISSUE THREAD

**Issue by eads** [newsdev/elex#204]

**Comment by palewire** [comment]
Confirmed. I saw this bug myself this morning in the AP data test.

**Comment by anthonyjpesce** [comment]
+1

**Comment by eads** [comment]
Finna roll a release tonight or over the weekend with this fix.

On Wed, Jan 27, 2016 at 1:51 PM, Anthony Pesce <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/204#issuecomment-175790276>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
so much for fixing this asap :/ :/ :/ -- will do it after NH

**Comment by jeremyjbowers** [comment]
So, https://github.com/newsdev/elex/commit/901b05e92b90fd01ed899ac543604fc8d2c6e38e appears to solve this issue -- @anthonyjpesce, @palewire and @eads, do y'all want to weigh in?

**Comment by anthonyjpesce** [comment]
The commit looks good, I can probably test it out properly later today. Thank you!

**Comment by eads** [comment]
Hmmm, it's not clear to me this is fixed using the data from 2016-02-20.

**Comment by jeremyjbowers** [comment]
I'll take a look again but probably not until AFTER super tuesday.

**Comment by jeremyjbowers** [comment]
Hey, @eads @anthonyjpesce @greglinch, thinking about *not* fixing this since folks have already fixed this in the frontend. Does anyone want this enough to warrant redoing their frontends?

**Comment by eads** [comment]
I'd rather fix my frontend and be consistent. Right now we're doing
percents two ways.

On Mon, Mar 21, 2016 at 9:36 AM, Jeremy Bowers <notifications@github.com>
wrote:

> Hey, @eads <https://github.com/eads> @anthonyjpesce
> <https://github.com/anthonyjpesce> @greglinch
> <https://github.com/greglinch>, thinking about *not* fixing this since
> folks have already fixed this in the frontend. Does anyone want this enough
> to warrant redoing their frontends?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/204#issuecomment-199281220>
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by anthonyjpesce** [comment]
I'm totally cool not fixing it

**Comment by jeremyjbowers** [comment]
Oh, man, I just realized that any stored data will be stored improperly. So the fix for this must do two things:
- [ ] Fix the percentages in new data
- [ ] Provide an example script to fix old data

**Comment by jeremyjbowers** [comment]
Okay, just talked to @wmandrews and he wants this too.

**Comment by jeremyjbowers** [comment]
Okay, @wmandrews @eads @anthonyjpesce @greglinch I have a test that now passes: a6ef0f2b61a30701d77bf64d246d077bb5aed0f3. Still need an example script to fix old data.

**Comment by eads** [comment]
Since our database is essentially ephemeral, fixing old data isn't an issue
for us. But an example script is still important of course :D

On Mon, Mar 21, 2016 at 3:52 PM, Jeremy Bowers <notifications@github.com>
wrote:

> Okay, @wmandrews <https://github.com/wmandrews> @eads
> <https://github.com/eads> @anthonyjpesce
> <https://github.com/anthonyjpesce> @greglinch
> <https://github.com/greglinch> I have a test that now passes: a6ef0f2
> <https://github.com/newsdev/elex/commit/a6ef0f2b61a30701d77bf64d246d077bb5aed0f3>.
> Still need an example script to fix old data.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/204#issuecomment-199447769>
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by anthonyjpesce** [comment]
Yeah we're already storing the raw data and transforms on separate tables, so it's less of an issue here as well. Anyway, many thanks!

**Comment by greglinch** [comment]
We're storing the old results and fixing that number on the front-end.

**Comment by eads** [comment]
@jeremybowers here's my thought: Let's roll any other fixes except for the
new field and this into another release. Then let's do those two and make
it a major new release (e.g. 2.0). Whatcha think?

On Tue, Mar 22, 2016 at 9:52 AM, Greg Linch <notifications@github.com>
wrote:

> We're storing the old results and fixing that number on the front-end.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/204#issuecomment-199825617>
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
I think that is fabulous.


contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])

**Comment by eads** [comment]
since I slightly messed up in being consistent about merging, this is now fixed on master
