### ISSUE TITLE
csvkit and elex don't coexist nicely

### ISSUE THREAD

**Issue by eads** [newsdev/elex#206]
csvkit requires python-dateutil 2.2, but elex requires 2.4.2

**Comment by eads** [comment]
closed in b76e7ad7d9d5d1af753adb926d1f9db422565615

**Comment by TylerFisher** [comment]
Hey this is a thing again?
<img width="1040" alt="screen shot 2016-10-20 at 9 59 37 pm" src="https://cloud.githubusercontent.com/assets/1077075/19584193/b14e10d8-9710-11e6-9221-7bcfd52211f9.png">

**Comment by eads** [comment]
oooh yes it is. dammit, someone had a PR to upgrade our reqs and I didn't think of this. workaround is downgrading dateutil; will fix over the weekend for the next release.
