### ISSUE TITLE
Please explain how to get NH township versus county level results via the Python API 

### ISSUE THREAD

**Issue by palewire** [newsdev/elex#214]
![of course i've slept why do you ask](https://media.giphy.com/media/YRHUxUsud3200/giphy.gif)

**Comment by jeremyjbowers** [comment]
Township are just results where `level="township"` and county are results where `level="county"`. The command to load results in NH will actually load all three levels -- state, county, and township. You can query out the ones you want after loading.

**Comment by jeremyjbowers** [comment]
```
e = Election(electiondate='2016-02-09', datafile=self.data_url, testresults=False, liveresults=True, is_test=False)
township_results = [z for z in e.results if z.level == 'township'```

**Comment by jeremyjbowers** [comment]
@palewire Does the explanation above work for you?

**Comment by palewire** [comment]
Yes. You are a hero.
