### ISSUE TITLE
Reporting unit's ID is not unique when including districts

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex#226]
The ID that Elex generates is not unique if you're loading district and non-district results. It seems that districts can have the same `reportingunitid` as other geographies. 

For example, New Hamspshire's District 2 has a `reportingunitid` of `30031`, just like the township of Campton.

Seems like you need to concatenate `raceid`, `unique_id`, `level` and `reportingunitid`.

**Comment by jeremyjbowers** [comment]
I think that `level` and `reportingunitid` are sufficient to solve this case.
