### ISSUE TITLE
Do you support the ``setzerocounts`` argument AP just told me about?

### ISSUE THREAD

**Issue by palewire** [newsdev/elex#227]

**Comment by eads** [comment]
Not yet!

On Fri, Feb 19, 2016 at 7:19 PM, Ben Welsh <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/227>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
