### ISSUE TITLE
Ballot measures not appearing as expected in CLI results

### ISSUE THREAD

**Issue by greglinch** [newsdev/elex#229]
It appears as though no ballot measure are coming through when generating results from CLI. 

*I did...* 
`$ elex results 2015-11-03 > ~/Downloads/results20151103.csv`

*I saw...* 
There were no `True` rows when filtering `is_ballot_measure` in the those results

*I expected...*
Based on @jeremyjbowers' suggestion, there should be `True` rows in the column for that election. I also checked and found no rows with `Yes` or `No` results.

Here's the file generated by that command (and converted to xlsx because GitHub wouldn't let me attached a csv): 
[results20151103.xlsx](https://github.com/newsdev/elex/files/146803/results20151103.xlsx)

**Comment by eads** [comment]
Thanks Greg.

On Thu, Feb 25, 2016 at 10:32 AM, Greg Linch <notifications@github.com>
wrote:

> It appears as though no ballot measure are coming through when generating
> results from CLI.
>
> *I did...*
> $ elex results 2015-11-03 > ~/Downloads/results20151103.csv
>
> *I saw...*
> There were no True rows when filtering is_ballot_measure in the those
> results
>
> *I expected...*
> Based on @jeremyjbowers <https://github.com/jeremyjbowers>' suggestion,
> there should be True rows in the column. I also checked and found no rows
> with Yes or No results.
>
> Here's the file generated by that command (and converted to xlsx because
> GitHub wouldn't let me attached a csv):
> results20151103.xlsx
> <https://github.com/newsdev/elex/files/146803/results20151103.xlsx>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/229>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
This is really weird. Hitting the AP directly does replicate this.

But if I curl the JSON and hit the file locally, the results are much different.

```
elex ballot-measures 2015-11-03 -d general.json
2016-02-25 12:06:24,093 (INFO) elex (v1.1.5) : Getting ballot positions for election 2015-11-03
id,unique_id,candidateid,ballotorder,description,last,polid,polnum,seatname
12480,12480,12480,1,Excess of Blue Book Est,Yes,2,6212,BB Retain Revenue
12481,12481,12481,2,Excess of Blue Book Est,No,3,7922,BB Retain Revenue
12482,12482,12482,1,Jeffco School Dist 1,Yes,2,6212,Recall Williams Dist 1
12483,12483,12483,2,Jeffco School Dist 1,No,3,7922,Recall Williams Dist 1
12486,12486,12486,1,Jeffco School Dist 2,Yes,2,6212,Recall Newkirk Dist 2
12487,12487,12487,2,Jeffco School Dist 2,No,3,7922,Recall Newkirk Dist 2
12490,12490,12490,1,Jeffco School Dist 5,Yes,2,6212,Recall Witt Dist 5
12491,12491,12491,2,Jeffco School Dist 5,No,3,7922,Recall Witt Dist 5
29157,29157,29157,1,Citizen Initiative,Yes,2,22712,1 - Promote Clean Elections
29156,29156,29156,2,Citizen Initiative,No,3,22718,1 - Promote Clean Elections
29158,29158,29158,1,$15 Million-PL Chapt 337,Yes,2,22712,2 - Housing Bonds
29159,29159,29159,2,$15 Million-PL Chapt 337,No,3,22718,2 - Housing Bonds
29161,29161,29161,1,$85 Million-PL Chapt 305,Yes,2,22712,3 - Transportation Bonds
29160,29160,29160,2,$85 Million-PL Chapt 305,No,3,22718,3 - Transportation Bonds
29177,29177,29177,2,Question 1,No,3,22718,Portland Minimum Wage
29178,29178,29178,1,Question 1,Yes,2,22712,Portland Minimum Wage
29179,29179,29179,2,Question 2,No,3,22718,Portland Scenic Views
29180,29180,29180,1,Question 2,Yes,2,22712,Portland Scenic Views
31873,31873,31873,2,Education Funding,Against,,28346,Education Funding
31872,31872,31872,1,Education Funding,Approval,,28345,Education Funding
31874,31874,31874,1,EducationFundAlt,42,,28347,EducationFundingAlternative
31875,31875,31875,2,EducationFundAlt,42A,,28348,EducationFundingAlternative
45404,45404,45404,1,Bipartisan Redistricting,Yes,2,36982,1 - Create Redistricting Commiss
45405,45405,45405,2,Bipartisan Redistricting,No,3,36981,1 - Create Redistricting Commiss
45407,45407,45407,1,,Yes,2,36982,2 - Prohibit Market Monopolies
45406,45406,45406,2,,No,3,36981,2 - Prohibit Market Monopolies
45409,45409,45409,2,,No,3,36981,3 - Legalize Recreational Mariju
45408,45408,45408,1,,Yes,2,36982,3 - Legalize Recreational Mariju
59113,59113,59113,1,SJR - 1,In Favor,2,44025,1 - Increase Homestead Exemption
59112,59112,59112,2,SJR - 1,Against,3,44026,1 - Increase Homestead Exemption
59111,59111,59111,1,HJR - 75,In Favor,2,44025,2 - Survivor Tax Exemption
59110,59110,59110,2,HJR - 75,Against,3,44026,2 - Survivor Tax Exemption
59109,59109,59109,1,SJR - 52,In Favor,2,44025,3 - State Officer Residency
59108,59108,59108,2,SJR - 52,Against,3,44026,3 - State Officer Residency
59106,59106,59106,1,HJR - 73,In Favor,2,44025,4 - Sports Team Raffles
59107,59107,59107,2,HJR - 73,Against,3,44026,4 - Sports Team Raffles
59104,59104,59104,1,SJR - 17,In Favor,2,44025,5 - Private Road Construction
59105,59105,59105,2,SJR - 17,Against,3,44026,5 - Private Road Construction
59102,59102,59102,1,SJR - 22,In Favor,2,44025,6 - Right to Hunt
59103,59103,59103,2,SJR - 22,Against,3,44026,6 - Right to Hunt
59100,59100,59100,1,SJR - 5,In Favor,2,44025,7 - Fund NonToll Roads
59101,59101,59101,2,SJR - 5,Against,3,44026,7 - Fund NonToll Roads
59098,59098,59098,2,Proposition 1,Against,3,44026,Houston Equal Rights
59099,59099,59099,1,Proposition 1,In Favor,2,44025,Houston Equal Rights
7694,7694,7694,1,,Yes,2,48346,1366-State Tax
7695,7695,7695,2,,No,3,48347,1366-State Tax
7696,7696,7696,1,,Yes,2,48346,1401-Animal Trafficking
7697,7697,7697,2,,No,3,48347,1401-Animal Trafficking```

**Comment by jeremyjbowers** [comment]
Welp, looks like `Election.national` defaults to `True` for some reason? Going to do this to fix:

- [ ] Flip `Election.national` to `False` by default
- [ ] Add a CLI flag `--national-only` to allow user to filter to only national-level results.
