### ISSUE TITLE
CSVs are double-spaced (?) in Excel

### ISSUE THREAD

**Issue by thomaswilburn** [newsdev/elex#232]
I'm not sure why Python's csv writer defaults to `\r\n` line endings given that the base dialect is supposed to be Excel compatible, but in Excel 2013 the result is that every other line is blank. I've been running the CSV through `sed "s/\r\n/\n/"` when I need to open it as a spreadsheet, but maybe it would make sense to just change the dialect if this is a problem for more than just me?

**Comment by eads** [comment]
womp womp

On Tue, Mar 1, 2016 at 7:43 PM, Thomas Wilburn <notifications@github.com>
wrote:

> I'm not sure why Python's csv writer defaults to \r\n line endings given
> that the base dialect is supposed to be Excel compatible, but in Excel 2013
> the result is that every other line is blank. I've been running the CSV
> through sed "s/\r\n/\n/" when I need to open it as a spreadsheet, but
> maybe it would make sense to just change the dialect if this is a problem
> for more than just me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/232>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
Yeah, this is oddly the default behavior for the Python CSV writer? https://docs.python.org/2/library/csv.html#csv.Dialect.lineterminator Anyone have a problem if I set `lineterminator='\n'` to solve this?

**Comment by eads** [comment]
Sounds good to me!

On Mon, Mar 21, 2016 at 9:39 AM, Jeremy Bowers <notifications@github.com>
wrote:

> Yeah, this is oddly the default behavior for the Python CSV writer?
> https://docs.python.org/2/library/csv.html#csv.Dialect.lineterminator
> Anyone have a problem if I set lineterminator='\n' to solve this?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/232#issuecomment-199282636>
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
Just saw http://stackoverflow.com/questions/1170214/pythons-csv-writer-produces-wrong-line-terminator which might be related, though I have a fix now.

**Comment by jeremyjbowers** [comment]
@thomaswilburn Got this in 1.2.5. https://pypi.python.org/pypi/elex/1.2.5
