### ISSUE TITLE
Elex crashes on startup

### ISSUE THREAD

**Issue by audreycarlsen** [newsdev/elex#233]
Installed pip from easy_install, then installed elex, but it's crashing on startup:

```
Traceback (most recent call last):
  File "/usr/local/bin/elex", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests==2.9.1
```

**Comment by eads** [comment]
Sounds like you should try a virtualenv. The supporting libraries don't
appear to be installed on your system despite pip installing elex.

On Wed, Mar 2, 2016 at 12:26 PM, Audrey Carlsen <notifications@github.com>
wrote:

> Installed pip from easy_install, then installed elex, but it's crashing on
> startup:
>
> Traceback (most recent call last):
>   File "/usr/local/bin/elex", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
>     working_set.require(__requires__)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
>     raise DistributionNotFound(req)  # XXX put more info here
> pkg_resources.DistributionNotFound: requests==2.9.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/233>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by ryanpitts** [comment]
Maybe you have a different `requests` release already installed? @audreycarlsen I wrote a walkthrough for the Knight-Mozilla fellows on how to set up `elex` inside a virtual environment -- you may already be familiar, but if not, maybe this is helpful: http://elex.readthedocs.org/en/1.2.1/install.html#install-walkthrough-with-virtualenv

**Comment by eads** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7681590-118011287_5-s1-v1.png?palette=1&width=246)

**Comment by audreycarlsen** [comment]
This worked! Thanks @ryanpitts

**Comment by eads** [comment]
Huzzah!

**Comment by ryanpitts** [comment]
awesome!
