### ISSUE TITLE
Minimize number of API calls for delegates

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#234]
- [ ] Export `AP_DELEGATE_REPORT_ID` to remove one API call.
- [x] Examine docs to see if we can get all necessary fields within a single call rather than two.

**Comment by eads** [comment]
could also cache AP_DELEGATE_REPORT_ID on first request

On Thu, Mar 3, 2016 at 6:58 AM, Jeremy Bowers <notifications@github.com>
wrote:

>
>    - Export AP_DELEGATE_REPORT_ID to remove one API call.
>    - Examine docs to see if we can get all necessary fields within a
>    single call rather than two.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/234>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
I investigated; there's no URL route that gets both state-level stuff and the difference over the last x days.

**Comment by jeremyjbowers** [comment]
Pushing this to 2.0 since we have a basic solution in place. https://github.com/newsdev/elex-loader/blob/master/scripts/prd/daemon.sh#L34

**Comment by eads** [comment]
I can tackle this one if you want to assign it to me. I have some thoughts
about how we could cache this on first request and alternately provide a
way to specify it via a cli flag.

On Tue, Mar 22, 2016 at 9:49 AM, Jeremy Bowers <notifications@github.com>
wrote:

> Pushing this to 2.0 since we have a basic solution in place.
> https://github.com/newsdev/elex-loader/blob/master/scripts/prd/daemon.sh#L34
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/234#issuecomment-199824641>
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
