### ISSUE TITLE
Hard-coded URL paths to the AP breaking our replay

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#235]
These two things contradict -- especially when called at the same time. One calls for election results and one calls for delegates.

<img width="537" alt="screen shot 2016-03-03 at 10 32 13 pm" src="https://cloud.githubusercontent.com/assets/109988/13517281/e4225866-e18f-11e5-8871-f98561e2a7ce.png">

<img width="560" alt="screen shot 2016-03-03 at 10 32 19 pm" src="https://cloud.githubusercontent.com/assets/109988/13517286/e8d1a894-e18f-11e5-8c27-2d84676e67c1.png">

**Comment by jeremyjbowers** [comment]
Fixed here: https://github.com/newsdev/elex/tree/235-feature

```pip install -e git+git@github.com:newsdev/elex.git@235-feature#egg=elex```

Need to check in with others to make sure this isn't destroying something they rely on.

**Comment by eads** [comment]
This is good. The alternate paths were always a hack, and not a very good
one.

On Thu, Mar 3, 2016 at 10:52 PM, Jeremy Bowers <notifications@github.com>
wrote:

> Fixed here: https://github.com/newsdev/elex/tree/235-feature
>
> pip install -e git+git@github.com:newsdev/elex.git@235-feature#egg=elex
>
> Need to check in with others to make sure this isn't destroying something
> they rely on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/elex/issues/235#issuecomment-192085762>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
