### ISSUE TITLE
Request to include is_ballot_measure on Race model

### ISSUE THREAD

**Issue by greglinch** [newsdev/elex#238]
We currently add it on our end and, in the save method, do this:
```
if self.racetype == "Ballot Issue":
    self.is_ballot_measure = True
```
It would be helpful if the Race model included `is_ballot_measure` out of the box:

https://github.com/newsdev/elex/blob/master/elex/api/models.py#L596

**Comment by jeremyjbowers** [comment]
I have this working in a branch. Because it introduces breaking changes (e.g., adds a field) I'll need to run it by @eads before I send it out.

**Comment by greglinch** [comment]
Totally understand, no rush. Glad to hear it's in the pipeline!

**Comment by jeremyjbowers** [comment]
@greglinch It's actually done in a feature branch. Will merge this in with a bunch of @eads changes and #204 in 2.0 probably in the next two weeks or so.

**Comment by eads** [comment]
I made a 2.0 branch and am PRing / merging these fixes into it.

**Comment by greglinch** [comment]
Thanks!
