### ISSUE TITLE
schematize stuff in docs into json schema

### ISSUE THREAD

**Issue by eads** [newsdev/elex#24]

**Comment by livlab** [comment]
I'm happy to take this one on if you can guide me on how to structure it.

**Comment by jeremyjbowers** [comment]
https://github.com/burningtree/awesome-json#json-schema-validators ?

**Comment by jeremyjbowers** [comment]
Pushing this one again. There will be more stuff on the Super Tuesday returns.

**Comment by jeremyjbowers** [comment]
Not sure this is really necessary now that we're a few elections under the belt. Plus, AP changes all the time without being too breaky - we get emails from them with the changes.
