### ISSUE TITLE
Implement conditional GET

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#250]
Here's my thought of how this would work.

- [ ] Elex checks to see if `ELEX_ETAG_STORE` contains any files named `etag.txt` which contains an ETAG hash returned by the AP. If there are no files or if the file has no hash value, Elex makes a GET request for data to the URL without sending a HEAD request.
- [ ] If there are ETAG files in the `ELEX_ETAG_STORE`, Elex will make a HEAD request to the AP and compare the ETAG value to what is in the directory.
- [ ] If the ETAG value from the HEAD request matches the ETAG value in the file, Elex will exit with status 0.
- [ ] If the ETAG value from the HEAD request does not match the file, Elex will issue a GET request for data and add the new ETAG to the file.

**Comment by eads** [comment]
Whether or not we use CacheControl, I think in general we should be storing the responses and returning them so that the caching is completely hidden to the Elex user.

* Elex checks a database (probably a simple filesystem db like a csv or pickled list) with url, etag combos.
* If url is not found in db, dispatch a get request (and cache).
* If url is found in db, dispatch HEAD request to check currently stored etag vs. live etag.
* If they don't match, dispatch a GET request (and cache).
* If they do match, read out data from cache.

**Comment by eads** [comment]
One reason to roll our own would be caching the parsed response and not the raw response and skipping all of elex for cache hits except writing to stdout.

**Comment by jeremyjbowers** [comment]
The only thing I don't _love_ about returning a cached response is that I would prefer to skip the loading step if we have cached content. Perhaps this can be the default behavior (returns cached content) and we can have a flag for `--exit-if-cached` or something.

**Comment by eads** [comment]
Hmmm yeah that's an excellent point. I just think for a whole variety of reasons it would be weird to run `elex results xx-xx-xxx` and get nothing.

How about this?

* By default, elex writes results to stdout whether cache hit or miss
* If it's a cache hit, still write results to stdout but exit with custom exit code (http://tldp.org/LDP/abs/html/exitcodes.html) -- e.g. exit code 3 or something.
* If the flag is provided and it's a cache hit, skip rendering too to save time.

Just throwing ideas around here.

**Comment by jeremyjbowers** [comment]
I like that. Anything I can catch in a bash script to prevent me from running the whole write-to-db cycle for existing data would be good.

**Comment by jeremyjbowers** [comment]
From the phone call, sounds like conditional `GET` is the proper solution. We can implement an `if-none-match` and will get a 304 if there is no new data and new data if there is some.
