### ISSUE TITLE
small fix to county roll up logic

### ISSUE THREAD

**Issue by eads** [newsdev/elex#266]
from Slack:

eads [10:19 AM] 
hey, quick thought — we can do this one later

+                    reporting_units = [
+                        r for
+                        r in self.reportingunits if
+                        r.level == 'township' and
+                        "Mail Ballots C.D." not in r.reportingunitname and
+                        r.fipscode == c
+                    ]

if you put that above all the sum( … ) statements
you can do

+                    counties[c]['precinctsreporting'] = sum([
+                        r.precinctsreporting for r in reporting_units])

jeremy.bowers [10:19 AM] 
Right
a sub-thing
[r.foo for r in reporting_units]

**Comment by jeremyjbowers** [comment]
Got this in 572a9b4e690e7620b764d4cc88352e94d3484513.
