### ISSUE TITLE
Division by zero when pulling 2012-11-06

### ISSUE THREAD

**Issue by mattdellavolpe** [newsdev/elex#271]
The below throws a division by zero exception when pulling 2012-11-06
https://github.com/newsdev/elex/blob/master/elex/api/models.py#L676

**Comment by jeremyjbowers** [comment]
Ah, a regression from a recent update.

**Comment by jeremyjbowers** [comment]
Got this in 572a9b4e690e7620b764d4cc88352e94d3484513. Thanks @mattdellavolpe!
