### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'NoneType' when querying 2012-11-06

### ISSUE THREAD

**Issue by mattdellavolpe** [newsdev/elex#272]
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
From line:
https://github.com/newsdev/elex/blob/master/elex/api/models.py#L678

**Comment by jeremyjbowers** [comment]
Yup, regression from a recent update.

**Comment by jeremyjbowers** [comment]
Got this in 572a9b4e690e7620b764d4cc88352e94d3484513. Thanks @mattdellavolpe!
