### ISSUE TITLE
Parallelize Race parsing

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#275]
It's the level at which we can do things non-serially. Thinking about greenlets.

**Comment by jeremyjbowers** [comment]
The `Election.get_race_objects` function is perfectly placed to do this.

**Comment by jeremyjbowers** [comment]
Might be able to do this with the stdlib multiprocessing.

**Comment by eads** [comment]
I'm a fan of joblib too: https://pythonhosted.org/joblib/

**Comment by eads** [comment]
I think you're right tho the multiprocessing Pool might be the best (and has no external dependencies).

**Comment by jeremyjbowers** [comment]
Working here; need to time this against the general and super tuesday. https://github.com/newsdev/elex/tree/275-parallel

**Comment by jeremyjbowers** [comment]
Tests are failing under tox.

**Comment by jeremyjbowers** [comment]
* [ ] Benchmark
* [ ] Why are tests failing in tox? (file handles)

**Comment by eads** [comment]
And Travis CI.

**Comment by jeremyjbowers** [comment]
Oh, wow, got the tests passing ... and it's slower.

Sigh. KILL YOUR DARLINGS.
