### ISSUE TITLE
Stale pinned requirements?

### ISSUE THREAD

**Issue by pmlandwehr** [newsdev/elex#279]
I've been putting together a build of `elex` using [`conda`](http://conda.pydata.org/docs/) for [conda-forge](https://conda-forge.github.io/). Y'all use some very specific pinnings in `requirements.txt`. I'll be sticking with them, but was wondering if those needed to be `==` or could also be `>=`. (Some of them are a few years stale...)

**Comment by eads** [comment]
They probably could, though I'd rather upgrade manually. I tend to be conservative that way. Can you point them out?

**Comment by pmlandwehr** [comment]
Sure:
* `cement 2.6.2` is from June 2015, while `2.10.2` is from July 2016.
* `pymongo 2.8` is from January 2016, while `3.3.0` is from July 2016.
* `python-dateutil 2.2` is from November 2013, while `2.5.3` is from April 2016.
* `requests 2.9.1` is from December 2015, while `2.11.1` is from August 2016

**Comment by eads** [comment]
Thanks!

**Comment by jeremyjbowers** [comment]
I should audit this. They're pinned but not for great reasons.
