### ISSUE TITLE
Duplicate id in Nov. 8 test results data download

### ISSUE THREAD

**Issue by greglinch** [newsdev/elex#282]
I'm using Elex 2.1.0 locally on my Mac, which runs Yosemite.

### I did 
I ran the following command in an attempt to manually reproduce the same issue after it appeared in my results system: 

`elex results '2016-11-08' -t > ~/Downloads/results20161108.csv`

### I saw
Importing it to my system, I got this error:

`File "<console>", line 2, in <module>`
`IntegrityError: duplicate key value violates unique constraint "results_resultcheck_pkey"`
`DETAIL:  Key (id)=(0-polid-65684-state-CO-1) already exists.`

And I confirmed this by checking the file: [results20161108.xlsx](https://github.com/newsdev/elex/files/452934/results20161108.xlsx)

### I expected 
The IDs to all come through as unique.

**Comment by jeremyjbowers** [comment]
Thanks Greg. It's on the list.

**Comment by eads** [comment]
Hey @greglinch -- I did some cursory tests and didn't see a duplicate id with the latest test data... 

What do you think?

**Comment by eads** [comment]
I'll test more and maybe roll this in with my mega test suite fun if I can swing it. But I'm inclined to release 2.3 and then move on to this. cc @jeremyjbowers

**Comment by jeremyjbowers** [comment]
I will confirm this tonight.

**Comment by greglinch** [comment]
Sorry for the delay, @eads @jeremyjbowers. I just got back in town after a trip. I haven't experienced this again during last week's testing, so I'd say definitely a low priority at this point.

**Comment by jeremyjbowers** [comment]
I think I stealthily fixed this in 2.1.x and forgot to close the ticket.


contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])
