### ISSUE TITLE
Bug: Elex doesn't show the version number anymore?

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#294]
```2016-10-10 18:14:11,003 (INFO) cement:app:elex : Getting results for election 2016-11-08```

In the place where `cement:app:elex` is now, there used to be something like `elex 2.1.0` and I think it should say that for handy debugging purposes.

**Comment by eads** [comment]
I don't think it ever did. But it can!

**Comment by greglinch** [comment]
It did. I've been a fan of this!

**Comment by eads** [comment]
Whoops! I'll fix :)
