### ISSUE TITLE
Confirmation whether value will be avilable in reporting_unit on election day

### ISSUE THREAD

**Issue by nituneema** [newsdev/elex#310]
Hello Team , 

We are using this settings value in the code
AP_ELECTION_DATE = '2016-11-08'
AP_IS_TEST = False
AP_LIVERESULTS = True
AP_TESTRESULTS = False

Below is the code snippet 
e = api.Election(electiondate=self.electiondate, datafile=ap_api_cachefile, testresults=settings.AP_TESTRESULTS, liveresults=settings.AP_LIVERESULTS, is_test=settings.AP_IS_TEST, statepostal='PA')
        filter_level = 'state'
        reporting_units = e.reporting_units
        state_reporting_units = [x for x in reporting_units if x.statepostal in self._include_states and x.level == filter_level]
        results = e.results
        self.state_results = [x for x in results if x.statepostal in self._include_states and x.level == filter_level ]
        if not self._contests:
            for contest in state_reporting_units:
                candidates = self.get_candidates_by_raceid(contest.raceid, contest.statepostal)
                self._contests.append(AP_Contest(contest, candidates))
        return self._contests

So we are extracting Contest value from "reporting_unit" object and candidate value from "results" object. with following setting 
AP_IS_TEST = True
AP_LIVERESULTS = False
AP_TESTRESULTS = True
We are getting data in reporting_unit. But with this setting 
AP_IS_TEST = False
AP_LIVERESULTS = True
AP_TESTRESULTS = False

We are not getting any data . Please confirm if we get data on election day.

**Comment by greglinch** [comment]
Hey, @nituneema. I'm also an Elex user. This is something completely on the AP end of things. AP doesn't have zeroed-out, non-test data until 2 a.m. ET on Election Day. As long as the test data works, you should be fine on Nov. 8.
