### ISSUE TITLE
Can we be a little less restrictive on the requirements?

### ISSUE THREAD

**Issue by TylerFisher** [newsdev/elex#314]
In particular, the lock to a pretty old version of requests is bungling some other dependencies in my system, but there hasn't been a major version bump in requests so we _should_ be okay to run with a newer version

**Comment by mileswwatkins** [comment]
It certainly sounds like we'd be fine to upgrade, [from their docs](http://docs.python-requests.org/en/master/dev/philosophy/#semantic-versioning).

**Comment by palewire** [comment]
I've pushed an upgrade to the master branch.
