### ISSUE TITLE
what exactly is meant by "ballot positions" in the current model?

### ISSUE THREAD

**Issue by eads** [newsdev/elex#44]

**Comment by jeremyjbowers** [comment]
A ballot position is an AP "candidate" that represents a non-person in a race, e.g., typically a ballot position or an issue. I've abstracted those out into this phrase, "BallotPosition" since it's what the AP tends to use.

**Comment by jeremyjbowers** [comment]
Ways you can tell something is a ballot position and not a real candidate:
* It is `officeID = 'I'`
* It only has a last (and not a first) name, and that name is like `yes` or `approve` or `no` or `disapprove`.

**Comment by jeremyjbowers** [comment]
I set a boolean, `is_ballot_id`, on CandidateReportingUnit objects. There's a test that passes, believe it or not!

**Comment by eads** [comment]
It's just an odd phrase. It's a lot like ballot order. But that's cool :D

**Comment by jeremyjbowers** [comment]
We could make it `ballot_issue`/`BallotIssue` instead?

**Comment by eads** [comment]
I like that nomenclature a lot better, but I wonder if keeping with AP's language makes more sense.

**Comment by jeremyjbowers** [comment]
`BallotMeasure`

**Comment by jeremyjbowers** [comment]
Closed in sha 13598ed120ca5462b831335356bf24142e12d579.
