### ISSUE TITLE
give this thing a name

### ISSUE THREAD

**Issue by eads** [newsdev/elex#59]
My humble suggestion: `Payne` after [Ethel Payne](https://en.wikipedia.org/wiki/Ethel_L._Payne).

**Comment by jeremyjbowers** [comment]
I can dig it, I think.

**Comment by eads** [comment]
Who should we run it by?

On Thu, Nov 12, 2015 at 1:55 PM, Jeremy Bowers <notifications@github.com>
wrote:

> I can dig it, I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newsdev/nyt-ap-elections/issues/59#issuecomment-156200882>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jeremyjbowers** [comment]
Think I might be backing something really neutral like `py-ap-elections` after a conversation with my folks.

**Comment by jeremyjbowers** [comment]
Maybe we can name the releases, e.g., v2016 is `Payne` and v2018 can be `Tarbel`, etc?

**Comment by jeremyjbowers** [comment]
Let's discuss this f2f on Tuesday.

**Comment by eads** [comment]
I know we're gonna discuss, but here's another idea: `ap-elex` or, even better, just `elex`.

I like 'elex' because it's the name of the command right now. Easy to remember.

**Comment by jeremyjbowers** [comment]
Oooh, elex is AWESOME.


contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])

**Comment by eads** [comment]
that's excellent!

**Comment by jeremyjbowers** [comment]
`elex`
