### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by eads** [newsdev/elex#99]

**Comment by rshorey** [comment]
I get 2 test failures in py3. @jeremyjbowers, I assume I should wait on the major issues you're working on before digging in?

**Comment by eads** [comment]
I worked a bit on this. There are actually more failures because our tests have multiple assertions. But I got it mostly working under Python3. But there's an issue with data order that's biting us that I intend to fix by removing sorting in the Python library (see #136).

Current progress is in the 0099-python3 branch. 

Using Python3 greatly increases performance (on my system using the reference implementation, 22s with Py3 vs 33s with Py2.7), so this is definitely worth it.
